Core/Google Drive datasource
docqai/docq pull request #135
Opened 2023-10-28 06:45 UTC by osala-eng

## Description

Please include a summary of the change, e.g. what the new feature # is and/or what bug # it fixes. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes/Implements #(issue/feature)

implements #134 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

2023-10-28 07:42 UTC, osala-eng reviewed
@janaka This is ready for a look, left a comment on `opendal` reader

2023-10-28 07:42 UTC, osala-eng commented on source/docq/data_source/googledrive.py
> +
@janaka opendal reader throws a scheme not enabled error for `gdrive` this will probably be updated in their next release. 
I've created an alternative reader to handle loading `gdrive` for now if opendal fails

2023-10-28 12:41 UTC, janaka commented on source/docq/manage_credetials.py
why do we need a separate table for this, what have you learnt since we spoke?

I think we discussed saving the refresh token etc as part of the space settings given they are credentials issued to Docq not the user.

2023-10-28 12:43 UTC, janaka commented on source/docq/data_source/googledrive.py
> +"""Google drive datasource test."""
TODO: remove "test" from doc str

2023-10-28 12:47 UTC, janaka commented on source/docq/services/google_drive.py
> +def list_folders(creds: dict) -> list[dict]:
no OpenDAL Python binding then?

2023-10-29 20:37 UTC, osala-eng commented on source/docq/manage_credetials.py
We are still saving the credentials as part of space settings for indexing and other space operations. We also need a way of storing them after obtaining them as the process redirects to Google Auth services and resets all forms before the user commits them.

2023-10-29 20:37 UTC, osala-eng commented on source/docq/data_source/googledrive.py
> +"""Google drive datasource test."""
Done.

2023-10-30 11:19 UTC, janaka commented on source/docq/manage_credetials.py
so it's temporary? can we not use session cache?

2023-11-06 12:30 UTC, janaka requested changes
Left some comments essentially around how the datasource settings are implemented in a way that couples the backend to the UI too much. 

If it makes it simpler drop the fancy folder selection UI for not (even though a nicer UX). But it feels like the creds setting still requires a new funcitonality unless we chang that to "paste your key here" which I don't think we should do.

2023-11-14 12:00 UTC, janaka requested changes

2023-11-20 06:04 UTC, osala-eng commented on source/docq/data_source/main.py
> +class SetFSHandler:
Removed this as discussed.

2023-11-20 06:05 UTC, osala-eng commented on source/docq/manage_documents.py
> +        website = _remove_ascii_control_characters(metadata.get("source_website", ""))
Sometimes the web reader includes the page anchor as part of the web address.

2023-11-20 07:56 UTC, janaka commented
Scanning through on my phone seems all good. Will look on my laptop in a bit.

2023-11-20 10:03 UTC, janaka approved these changes
LGTM - Nice work cleaning it up. 

Can you please make sure to do a full QA. That personal ask issue is the only known issue iirc.

Also, the integration tests broke for some reason a few PRs back, I couldn't figure it out so left it. Worth checking that as well.

2023-11-20 14:15 UTC, osala-eng commented
> LGTM - Nice work cleaning it up.
> 
> Can you please make sure to do a full QA. That personal ask issue is the only known issue iirc.
> 
> Also, the integration tests broke for some reason a few PRs back, I couldn't figure it out so left it. Worth checking that as well.

Okay, Doing a full QA

2023-11-21 08:10 UTC, merged