feat/Enable file upload in chat window
docqai/docq pull request #187
Opened 2023-12-16 08:24 UTC by osala-eng

## Description

Enable users to upload a file within chat window

![image](https://github.com/docqai/docq/assets/64925863/156c4112-cb0e-4867-bd2f-054875bc6666)

Closes #181 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

2023-12-27 13:05 UTC, janaka commented
can you remind me where this is at pls. Any of the changes we discussed in the sync in yet?

2023-12-28 04:39 UTC, osala-eng commented
> can you remind me where this is at pls. Any of the changes we discussed in the sync in yet?

This is not yet updated as per the requested changes. Should be ready later today.

2024-01-03 11:18 UTC, osala-eng commented
@janaka This is ready for review.

2024-01-08 12:06 UTC, janaka commented
just about to pull the branch and check. One thought ahead of that, how we handle database schema migrations. I think this PR will fail in production due to the new column.

2024-01-08 12:10 UTC, janaka commented
![image](https://github.com/docqai/docq/assets/51779/d1bacbf3-f60f-491a-98ea-c704ec1fa556)

2024-01-08 12:17 UTC, janaka commented
If we were using an ORM like SqlAlchemy that would have db migration handling functionality.

What we could do is to have a migrations() function, that calls a list of migration functions, that runs on setup(). we already handle table creation so can ignore that. Adding columns is the main one. Can be handled with `ALTER TABLE`. There are some constraints this way I think. Like new columns can only be added to the end of the column list, need to check if the column exists already before running the alter etc.

2024-01-08 12:32 UTC, janaka commented
I pushed a sample structure for db migration code. Let's try it out with this change.

2024-01-09 16:13 UTC, janaka commented
@osala-eng In case you haven't spotted the error below. Thread space index doesn't seem to be loading during ask. likely also the cause of the "Empty Response".

<img width="326" alt="image" src="https://github.com/docqai/docq/assets/51779/a18f0cc0-a893-456a-b11a-f01ed6783473">

2024-01-09 16:26 UTC, janaka commented
Looks like the index store is getting created in `SHARED` rather than `THREAD`. Likely the space type isn't getting passed correctly when create index is called.

2024-01-10 16:14 UTC, janaka commented on source/docq/manage_spaces.py
> +@trace.start_as_current_span("manage_spaces.list_thread_spaces")
functions shouldn't be blanket decorated with a trace span because that would make the trace hard to navigate and understand in Honeycomb (or other UI).

there's probably little benefit from these sorts of wrapper functions being traced. The functions that contain logic are valuable to trace. 

also note some libraries like sqlite are auto instrumented so we don't have to manually instrument unless we want some data it's not tracking. You can see the full list of `opentelemetry-instrumentation-*` dependencies in pyproject.toml for auto instrumented libs

2024-01-10 16:24 UTC, janaka requested changes
I think the UI for Chat history and documents needs to be more consistent at the top level. That is both rendered inside expanders. Unfortunately, that means we cannot reuse the document list design from admin settings because (annoyingly) streamlit doesn't allow expander inside and expander.

Can you create a new list rendering that works here? and lets call this section here "Knowledge"

![image](https://github.com/docqai/docq/assets/51779/0610e9a9-e08f-4f3b-a450-c946400090d9)

2024-01-10 16:24 UTC, janaka commented on web/utils/layout.py
> +    _render_chat_file_uploader(feature, len(chat_history) if chat_history else 0)
the `chat_id` param is a bit confusing here. It's used for a component key inside the function, I get that but why is the value here calculated from the len of the chat_history. Seems off.

2024-01-10 19:57 UTC, osala-eng commented on web/utils/layout.py
> +    _render_chat_file_uploader(feature, len(chat_history) if chat_history else 0)
Okay, let me rename this.

2024-01-10 19:58 UTC, osala-eng commented
> I think the UI for Chat history and documents needs to be more consistent at the top level. That is both rendered inside expanders. Unfortunately, that means we cannot reuse the document list design from admin settings because (annoyingly) streamlit doesn't allow expander inside and expander.
> 
> Can you create a new list rendering that works here? and lets call this section here "Knowledge"
> 
> ![image](https://private-user-images.githubusercontent.com/51779/295633179-0610e9a9-e08f-4f3b-a450-c946400090d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTY4OTIsIm5iZiI6MTcwNDkxNjU5MiwicGF0aCI6Ii81MTc3OS8yOTU2MzMxNzktMDYxMGU5YTktZTA4Zi00ZjNiLWE0NTAtYzk0NjQwMDA5MGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE5NTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZmRjZjMzODBhMTU1NzQwMTIzOTc1YzYxYjViMjIyNTFkMmMxNTU3YWIzOGI2NjZiOGJhY2ZmMjkyOGM3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Wtxwv730eT7Sd2Bn25dlsNGVfcICQX5g9wzRI6VbZg)

Okay

2024-01-10 19:59 UTC, osala-eng commented on source/docq/manage_spaces.py
> +@trace.start_as_current_span("manage_spaces.list_thread_spaces")
Okay, let me take a look at this.

2024-01-12 12:32 UTC, janaka commented on source/docq/db_migrations.py
> +                        span.set_attribute("migration_successful", "false")
In addition, I think this should be flagged as an error span using the same set_status and record_exception pattern below. That way in the trace UI it gets picked up as an error and highlighted.

2024-01-12 12:33 UTC, janaka commented on source/docq/db_migrations.py
> +                    logging.info("db_migrations.add_space_type_to_spaces, space_type column does not exist, adding it")
adding these logs as span events as well probably useful.

2024-01-12 17:28 UTC, janaka commented
@osala-eng Let me know once you rebase.

2024-01-13 00:24 UTC, osala-eng commented on source/docq/db_migrations.py
> +                    logging.info("db_migrations.add_space_type_to_spaces, space_type column does not exist, adding it")
Okay

2024-01-13 02:00 UTC, osala-eng commented
@janaka This is ready for another look, I've made the requested changes.

<img src="https://github.com/docqai/docq/assets/64925863/bb48dce2-45f9-427b-967c-b7c9c2f6cf12" width="400px"/>

2024-01-13 10:14 UTC, janaka commented
I don't think the file delete is working properly. When I delete the file and ask a question it's still rendering it as a source in responses. Maybe the thread index isn't being removed etc.

2024-01-13 10:36 UTC, janaka commented
@osala-eng can you try style the `New chat` button to appear left of the file uploader bar pls

![image](https://github.com/docqai/docq/assets/51779/5bc0d292-8caa-4b3e-883c-164b7ff57500)

2024-01-13 11:55 UTC, janaka commented
Can't remember if we discussed this, when a file is being indexed is it easy to indicate the status?

2024-01-13 12:18 UTC, janaka commented
note sure if I broke it, but there seems to be two problems 

1) it seems like every chat is running a reindex. 
2) retrieval isn't working as it should based on my RAG fix. i.e. "Who are the cofounders of Docq.AI?" was working against the pitch deck file. It's not now.

2024-01-13 12:37 UTC, janaka commented
> note sure if I broke it, but there seems to be two problems
> 
> 1. it seems like every chat is running a reindex.
> 2. retrieval isn't working as it should based on my RAG fix. i.e. "Who are the cofounders of Docq.AI?" was working against the pitch deck file. It's not now.
> 
> It still worked against a shared space with the pitch deck file. But not when the same file is uploaded into the thread.

FIXED. 

fixing the reindex issue has also resolved this.

2024-01-15 09:19 UTC, osala-eng commented
Closes #192

2024-01-16 08:38 UTC, osala-eng commented
@janaka I've made the requested changes.

![image](https://github.com/docqai/docq/assets/64925863/ec215f25-323a-4c99-bf65-bc2e451d9eb5)

2024-01-20 13:45 UTC, janaka approved these changes
@osala-eng functionally this all works great. There are still some UI styling issues that need addressing. But I'm going to merge this PR and cut an issue for that.

2024-01-20 13:54 UTC, merged