Feat/chrome extension integration
docqai/docq pull request #217
Opened 2024-02-12 07:19 UTC by osala-eng

## Chrome extension integration

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

2024-02-12 08:48 UTC, osala-eng commented
jwt library - https://pypi.org/project/jwt/

2024-02-13 00:50 UTC, janaka requested changes

2024-02-13 00:50 UTC, janaka commented on web/api/utils.py
>      #TODO: add token validation logic
```suggestion
```

2024-02-13 00:50 UTC, janaka commented on web/api/templates.py
> +"""HTML page templates."""
as discussed, we don't want to render HTML from API endpoints especially in the chrome extension case the HTML can exist in the extension.

2024-02-13 00:50 UTC, janaka commented on web/api/utils.py
> +    def get_current_user(self: Self) -> UserModel:
this doesn't seem to be used anaywhere, can we delete?

2024-02-13 00:50 UTC, janaka commented on web/api/hello_handler.py
> +class EchoWebSocket(tornado.websocket.WebSocketHandler):
what's this for?

2024-02-13 00:50 UTC, janaka commented on web/api/chat_thread_handler.py
> +        thread_id = self.get_argument("id", None)
thread_id should be in the path not ha query string

e.g. /thread/{thread_id}

2024-02-23 11:30 UTC, janaka commented
@osala-eng this at a good spot for me to take a look this evening?

2024-02-23 17:09 UTC, osala-eng commented
> @osala-eng this at a good spot for me to take a look this evening?

I still have to fix a bug in RAG, then it'll be ready for a review

2024-02-24 12:35 UTC, janaka commented on web/api/utils.py
> +            api_key = self.get_argument("key")
General: no sure if you are mid changes as when I follow the code it seems like the validation is still using the current preshared key method. So the JWT code paths are being used? are you mid unwinding some stuff based on our chat on Mon?

On this line: this seems a pretty significant change. why has the code changed here for extracting the token from the "Authorization" header? As I understand this is now searching the query string and request body for an arg called "key", correct? AFAIK the standard is for the jwt token to be sent in exactly the same way this function was already handling in the Authorization header as  Bearer token.

2024-02-24 12:39 UTC, janaka commented on web/api/token_handler.py
> +    def token_error(self: Self, reason: str, status: int = 400) -> None:
why not `raise HTTPError` like elsewhere? iirc that handles the writing the error out to the response etc?

2024-02-24 12:48 UTC, janaka commented on web/api/utils.py
> +            api_key = self.get_argument("key")
ok I see, you've move some of the code elsewhere. Still don't understand the whole get_arguments bit.

2024-02-24 12:52 UTC, janaka commented on web/api/base.py
> +        scheme, token = auth_header.split(" ")
ok I now see you've refactored that token logic here. I vaguely see the reason but this doesn't feel like the best way to re-arrange the code. It looked like this get_curent_user() method is called from the authenticated() decorator. Why not have this code there or as a static in utilities? also this function isn't actually getting the current user in the same way as elsewhere as in load from the database?

2024-02-24 13:14 UTC, janaka commented on web/api/base.py
> +class BaseRequestHandler(RequestHandler):
general comment on these base handlers: it makes sense to have them to encapsulate the things that 1) depend on the HTTP request context 2) need enforcing and consistency typically cross-cutting.

Again, generally multiple base classes are ok if there's genuinely sub categories of request with extra functionality. 

Having said it doesn't see like we need two base classes here unless I missed something. One is fine for now, you can fold the rag one into the other.

2024-02-24 13:20 UTC, janaka commented on web/api/base.py
> +        scheme, token = auth_header.split(" ")
ok so the get_current_user function name is a tornado build-in thing. Bear in mind that all this in Tornado is in the context of serving web pages for a web directly rather than a REST API that another app is accessing.

2024-02-24 14:42 UTC, janaka commented on web/api/thread_handler.py
> +@st_app.api_route(r"/api/([^/]+)/thread/([^/]+)?")
I added functionality to the api_route decorator so you can define path args like /api/threads/{thead_id}/items.

Pushed the code into this branch but untested. Can you test an replace with this method everywhere pls

2024-02-24 14:45 UTC, janaka commented on web/api/space_handler.py
> +class FileUploadHandler(BaseRagRequestHandler):
guess this is a copy past rename miss.

2024-02-24 14:46 UTC, janaka commented on web/api/space_handler.py
> +@st_app.api_route(r"/api/space")
endpoint name though be plural so `/spaces/` trying to follow REST here.

2024-02-24 14:47 UTC, janaka commented on web/api/space_handler.py
> +        """GET /api/space?thread_id=x."""
following the above comment this should be a path arg rather than a query string.

so `api/spaces/{thread_id}`

2024-02-24 15:18 UTC, janaka commented on web/api/space_handler.py
> +            if request.space_type == "thread":
feedback: have you thought about how this will work when I need to create a space that's one of the other types? we don't need to code that up now but the design here should be able to cater for those when we do. So the request model should have the space type as a property. The handler code should switch on that type. Throw a not implemented for the other types.

I've gone ahead a refactored this to cover most. The response model probably needs  little more though based on the other types of spaces. I made thread id optional ont he response model.

2024-02-24 15:23 UTC, janaka commented on web/api/space_handler.py
I added some comments from VS Code but they aren't here...

2024-02-24 15:29 UTC, janaka commented on web/api/space_handler.py
> +@st_app.api_route("/api/spaces/{space_id}")
route names for endpoints operating directly on domain entities should be plural. So `spaces` rather than `space`.

Given how Tornado and our api_route decorator works I think this is best achieved by splitting the handler classes like this. If we did it on the one we'd have to make space id optional and that makes it more complicated. The new path arg handler I added doesn't allow optional and I don't think we want to add that. Other frameworks handle this by allowing defining route path on both the class level and the action handling function level.

2024-02-24 16:25 UTC, janaka commented on web/api/history_handler.py
> +    /api/v1/<chat|rag>/thread/{thread_id}/history - history belongs to a thread hence resource hierarchy in the URL.
pls adjust to handle these route patterns

2024-02-24 16:26 UTC, janaka commented on web/api/file_upload_handler.py
> +        thread_id: int (required) - The thread id.
is a thread id acutally used here or just out of date doc string?

2024-02-24 16:27 UTC, janaka commented on web/api/thread_handler.py
> +    /api/v1/{thread_type}/threads/ - list threads. should default to page 1 and page_size 10 or 20 or something.
pls adjust to handle these route patterns

2024-02-24 16:40 UTC, janaka commented on web/api/space_handler.py
> +                        request.thread_id
it feels off that this handler for spaces has logic to create a thread. The calling client should have the logic to create the thread using the /threads endpoint.

2024-02-24 17:09 UTC, janaka commented on web/api/base_handlers.py
> +        return space
I don't think these two should be here. See my comments elsewhere on being stateless for domain logic and not having a controller.

2024-02-24 17:38 UTC, janaka commented on web/api/file_upload_handler.py
> +        m_documents.upload(fname, fileinfo['body'], self.space)
security: should have a few guardrails here like
- check file size and have a limit on size
- sanitize the file name and truncate to something reasonable like 200 char.

2024-02-25 23:34 UTC, osala-eng commented on web/api/auth_handler.py
> +@st_app.api_route("/api/auth/login")
Done

2024-02-25 23:35 UTC, osala-eng commented on web/api/chat_history_handler.py
> +class PostRequestModel(CamelModel):
Done

2024-02-25 23:35 UTC, osala-eng commented on web/api/templates.py
> +"""HTML page templates."""
Done

2024-02-25 23:36 UTC, osala-eng commented on web/api/utils.py
> +    def get_current_user(self: Self) -> UserModel:
This sets the current user

2024-02-25 23:36 UTC, osala-eng commented on web/api/chat_thread_handler.py
> +        thread_id = self.get_argument("id", None)
Done

2024-02-25 23:39 UTC, osala-eng commented on web/api/utils.py
> +            api_key = self.get_argument("key")
This is here because we are using both API_KEY, and JWT_TOKEN

2024-02-25 23:40 UTC, osala-eng commented on web/api/token_handler.py
> +    def token_error(self: Self, reason: str, status: int = 400) -> None:
I did this to get custom error response, `raise HTTPError` sends and HTLM page by default

2024-02-25 23:43 UTC, osala-eng commented on web/api/thread_handler.py
> +@st_app.api_route(r"/api/([^/]+)/thread/([^/]+)?")
Done

2024-02-25 23:43 UTC, osala-eng commented on web/api/space_handler.py
> +class FileUploadHandler(BaseRagRequestHandler):
Done

2024-02-25 23:44 UTC, osala-eng commented on web/api/space_handler.py
> +@st_app.api_route(r"/api/space")
Done

2024-02-25 23:44 UTC, osala-eng commented on web/api/space_handler.py
> +        """GET /api/space?thread_id=x."""
Done

2024-02-25 23:46 UTC, osala-eng commented on web/api/space_handler.py
> +            if request.space_type == "thread":
Okay, I've refactored this to add the `space_type` as a path parameter `/api/v1/spaces/space_type/`

2024-02-25 23:47 UTC, osala-eng commented on web/api/space_handler.py
> +@st_app.api_route("/api/spaces/{space_id}")
Okay

2024-02-25 23:50 UTC, osala-eng commented on web/api/file_upload_handler.py
> +        thread_id: int (required) - The thread id.
moved this to path_args

2024-02-25 23:50 UTC, osala-eng commented on web/api/thread_handler.py
> +    /api/v1/{thread_type}/threads/ - list threads. should default to page 1 and page_size 10 or 20 or something.
Done

2024-02-25 23:52 UTC, osala-eng commented on web/api/base_handlers.py
> +        return space
Okay I'm taking these off.

2024-02-25 23:52 UTC, osala-eng commented on web/api/file_upload_handler.py
> +        m_documents.upload(fname, fileinfo['body'], self.space)
Okay

2024-02-25 23:53 UTC, osala-eng commented on web/api/space_handler.py
> +                        request.thread_id
Okay, let me remove the logic for creating thread here.

2024-02-26 12:32 UTC, osala-eng commented on web/api/base.py
> +class BaseRequestHandler(RequestHandler):
Done

2024-03-01 20:23 UTC, janaka commented
@osala-eng what's the update with this. Are the revisions we discussed done? really would like to get this one out ASAP. We need to move on to the Slack integration.

2024-03-04 06:21 UTC, osala-eng commented
> @osala-eng what's the update with this. Are the revisions we discussed done? really would like to get this one out ASAP. We need to move on to the Slack integration.

Yes I've made all the changes as we discussed.

2024-03-04 06:22 UTC, osala-eng reviewed
All changes made as requested

2024-03-06 21:04 UTC, janaka requested changes
Mostly looks great but still a few bits to tweak and some questions. Hopefully I'm not contradicting anything I said before :) If you can respond inline tomo (Thur AM) that would be great. Want to merge by Fri.

2024-03-07 07:19 UTC, osala-eng commented on source/docq/manage_spaces.py
> +def get_space(space_id: int, org_id: int) -> Optional[SPACE]:
This should be able to get all sace_types

2024-03-07 07:19 UTC, osala-eng commented on source/docq/manage_spaces.py
> +        sqlite3.connect(get_sqlite_system_file(), detect_types=sqlite3.PARSE_DECLTYPES)
I must have missed this during a rebase.

2024-03-07 07:19 UTC, osala-eng commented on web/api/base_handlers.py
> +            member_orgs = m_orgs.list_organisations(user_id=self.current_user.uid)
Done

2024-03-07 07:21 UTC, osala-eng commented on web/api/spaces_handler.py
>  @st_app.api_route("/api/v1/spaces/{space_type}")
We said to leave it this way in the previous discussion. Anyway let me remove it as a path parameter to fix it.

2024-03-07 07:21 UTC, osala-eng commented on web/api/token_handler.py
> +        token = self.get_argument("token", None)
Fixed

2024-03-07 07:21 UTC, osala-eng commented on web/api/token_handler.py
> +        token = self.get_argument("token", None)
Fixed

2024-03-07 07:23 UTC, osala-eng commented on web/api/spaces_handler.py
> +        space = get_space(self.selected_org_id, space_id, space_type)
Ok, Let me modify this to use the space_type from the `get_space()` method

2024-03-07 07:24 UTC, osala-eng commented on web/api/rag_completion_handler.py
> +    persona_key: Optional[str] = Field(None)
Okay

2024-03-08 20:49 UTC, janaka approved these changes
Looks great. nice work.

2024-03-08 21:02 UTC, janaka commented
I'll merge this in.

2024-03-08 21:15 UTC, merged