feat: Added slack chat integration.
docqai/docq pull request #236
Opened 2024-03-08 21:58 UTC by osala-eng

## Description

Slack chat bot integration

Implements #227 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

2024-03-08 22:05 UTC, osala-eng commented
@janaka  I've setup slack chat bot. you can review this and tell me what you think.

I've also added the sample chat bot to the Docq.AI's slack work space you can try that out aswell.

2024-03-08 23:22 UTC, janaka commented
Great. I'll take a look.

2024-03-09 00:05 UTC, janaka commented
How do I do RAG? Or you waiting for the updated Web API live?

2024-03-09 00:35 UTC, osala-eng commented
> How do I do RAG? Or you waiting for the updated Web API live?

This just implements chat comletion as described in #227, once we get this approved i'll use it to implement Retrival in #228

2024-03-09 15:03 UTC, janaka commented
great, I'll take a look at the code this weekend. 

I shipped the new Web API btw.

2024-03-09 15:19 UTC, janaka reviewed
Looks like the whole integration is webhooks based? 

This code should be part of the API I think. It also should be designed as a general webhook handler ideally.

2024-03-19 19:41 UTC, janaka requested changes
See comments. Please respond inline. 

I've not paid attention to the integrations setting / install stuff because it seems you are still working on the changes we discussed, moving those to the Admin Section.

2024-03-19 19:41 UTC, janaka commented on source/docq/integrations/slack.py
> +"""
Can you explain the data in this table pls. it's not obvious to me.

I don't love having Slack specific tables. It's OK that you started like this to get the whole thing up and running end to end. 

I'm wondering if we should iterate to a similar/same pattern as config for data sources.

2024-03-19 19:41 UTC, janaka commented on source/docq/setup.py
> +        slack._init()
pls put this inside and integrations._init() and call that here.

2024-03-19 19:41 UTC, janaka commented on source/docq/support/auth_utils.py
> +        name = SESSION_COOKIE_NAME
this shouldn't be here now right? That value should be passed in.

and name should not be Optional therefore.

2024-03-19 19:41 UTC, janaka commented on source/docq/support/auth_utils.py
> +    if expiry is None:
thinking it makes more sense for this function param to be`ttl` with the default  set to `TTL_HOURS`. Also renamed to COOKIE_DEFAULT_TTL_HOURS.

2024-03-19 19:41 UTC, janaka commented on source/docq/support/auth_utils.py
> +    if expiry is None:
unless I'm missing a use case.

2024-03-19 19:41 UTC, janaka commented on web/api/integration/slack/slack_application.py
> +)
what's going on here? this seems off with sqlite3 being called directly. Database calls should all be contained strictly within the data layer.

2024-03-19 19:41 UTC, janaka commented on web/api/integration/slack/oauth_flow.py
> +    def sqlite3(
same comment here re: sqlite

2024-03-19 19:41 UTC, janaka commented on web/api/integration/slack/chat_handler.py
> +"""Slack chat action handler."""
is `chat` a category of Slack events? so the pattern is we'll create a separate hanlder file to handle each category?

2024-03-19 19:41 UTC, janaka commented on web/api/integration/slack/chat_handler.py
> +"""Slack chat action handler."""
Generally worth referencing links to Slack docs.

2024-03-22 23:00 UTC, osala-eng commented on source/docq/integrations/slack.py
> +"""
Added comments on this.

2024-03-22 23:00 UTC, osala-eng commented on source/docq/setup.py
> +        slack._init()
Done

2024-03-22 23:00 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +        name = SESSION_COOKIE_NAME
Created a separate method for this.

2024-03-22 23:01 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +    if expiry is None:
Done.

2024-03-22 23:01 UTC, osala-eng commented on web/api/integration/slack/slack_application.py
> +)
Moved this to data layer.

2024-03-22 23:04 UTC, osala-eng commented
@janaka I've updated the changes as requested and implemented end to end slack chat with docq bot using RAG.

![image](https://github.com/docqai/docq/assets/64925863/728dbde3-eed7-4075-88e9-06765a72fce7)

2024-03-22 23:05 UTC, janaka commented
Great. Will take a look tomorrow.

2024-03-23 13:10 UTC, janaka commented
@osala-eng sorry, I merged the Llama Index update last night. Can you rebase and check all works. Mainly with the bits that bit the Web API

2024-03-24 16:31 UTC, osala-eng commented
> @osala-eng sorry, I merged the Llama Index update last night. Can you rebase and check all works. Mainly with the bits that bit the Web API

Okay, let me rebase and test this.

2024-03-24 16:33 UTC, janaka commented
great - do you have one or two tests for any of the new functionality build
for Slack and Chrome. Would be handy to know there's something.

On Sun, 24 Mar 2024 at 16:31, Jashon Osala ***@***.***> wrote:

> @osala-eng <https://github.com/osala-eng> sorry, I merged the Llama Index
> update last night. Can you rebase and check all works. Mainly with the bits
> that bit the Web API
>
> Okay, let me rebase and test this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/docqai/docq/pull/236#issuecomment-2016861975>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMUQYUMGEMXMN3SJWLRRTYZ35WVAVCNFSM6AAAAABENPVKL6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJWHA3DCOJXGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-25 13:10 UTC, osala-eng commented
@janaka There is a problem with [main](https://github.com/docqai/docq/tree/main) - I'll rebase this branch once that is sorted.

2024-03-25 18:13 UTC, janaka commented
What's the issue on main branch? Seem to be ok, test passed etc.

2024-03-27 20:02 UTC, janaka commented
Was that to do with your local virtual environment?

2024-03-27 21:06 UTC, osala-eng commented
Yes, it was my local env.

On Wed, 27 Mar 2024, 23:02 Janaka Abeywardhana, ***@***.***>
wrote:

> Was that to do with your local virtual environment?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/docqai/docq/pull/236#issuecomment-2023862456>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APPLBJ5A64WIP7L3OPUJVATY2MJVVAVCNFSM6AAAAABENPVKL6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRTHA3DENBVGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-29 17:30 UTC, osala-eng commented
This is ready for you now.

On Fri, Mar 29, 2024 at 5:52 PM Janaka Abeywardhana <
***@***.***> wrote:

> @osala-eng <https://github.com/osala-eng> what's the state of this PR?
> are you still making changes or over to me?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/docqai/docq/pull/236#issuecomment-2027346078>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APPLBJ5FVRPI5WCVXX6DJITY2VWZXAVCNFSM6AAAAABENPVKL6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRXGM2DMMBXHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-04 23:39 UTC, janaka reviewed
@osala-eng I pushed a bunch of refactors. Any chance you can do a little quick test.

2024-04-05 05:44 UTC, osala-eng commented
> @osala-eng I pushed a bunch of refactors. Any chance you can do a little quick test.

Okay let me do a quick test and get back to you.

2024-04-05 07:04 UTC, osala-eng reviewed
This dosent work fully as some of the functionality has been disabled.

2024-04-05 07:04 UTC, osala-eng commented on source/docq/integrations/slack/slack_oauth_flow.py
> +    #         raise BoltError("Login to Docq before installing the slack app.")
@janaka I see you've commented out some of the code.

2024-04-05 11:10 UTC, janaka commented on source/docq/integrations/slack/slack_oauth_flow.py
> +    #         raise BoltError("Login to Docq before installing the slack app.")
Seemed like those weren't being called. Maybe my VS Code search wasn't working properly. If you uncomment that does it work.

2024-04-05 13:43 UTC, janaka commented on source/docq/integrations/slack/slack_oauth_flow.py
> +    #         raise BoltError("Login to Docq before installing the slack app.")
great! mind adding a few comments to document that logic.

Assume all is working as expected at this point?

2024-04-05 13:44 UTC, osala-eng commented on source/docq/integrations/slack/slack_oauth_flow.py
> +    #         raise BoltError("Login to Docq before installing the slack app.")
Yes, I've tested and all is working as expected.

2024-04-05 13:46 UTC, osala-eng commented on source/docq/integrations/slack/slack_oauth_flow.py
> +    #         raise BoltError("Login to Docq before installing the slack app.")
Let me add a few comments on this.

2024-04-05 13:57 UTC, osala-eng commented
@janaka This is now ready.

2024-04-05 22:56 UTC, janaka commented
@osala-eng did you write down anything / ref a link on how the values for the following were generated?


SLACK_CLIENT_ID
SLACK_CLIENT_SECRET
SLACK_SIGNING_SECRET

2024-04-05 22:59 UTC, janaka commented on source/docq/integrations/slack/slack_application.py
> +USER_SCOPES = ["admin"]
@osala-eng wondering if we can have a lesser scope here.

2024-04-06 15:06 UTC, janaka commented
> @osala-eng did you write down anything / ref a link on how the values for the following were generated?
> 
> SLACK_CLIENT_ID SLACK_CLIENT_SECRET SLACK_SIGNING_SECRET

@osala-eng I just remembered about the other repo with the manifest file which answer my original question sufficiently.

New related question about the env var names. You went with the SDK built-in names rather than our usual pattern of prefixing with "DOCQ_". Was that intentional for reasons like it's the only way to use the SDK? I wanted to check before refactoring to save myself some pain :)

2024-04-06 15:22 UTC, osala-eng commented on source/docq/integrations/slack/slack_application.py
> +USER_SCOPES = ["admin"]
The only scope that you can remove without affecting the functionality is `admin` but then anyone within a slack team will be able to install the application. Currently, only admins can install the application.

For the rest, we are mostly requesting read access, except for chat, where we need write access to enable the bot to respond to mentions.

2024-04-06 15:28 UTC, osala-eng commented
> > @osala-eng did you write down anything / ref a link on how the values for the following were generated?
> > SLACK_CLIENT_ID SLACK_CLIENT_SECRET SLACK_SIGNING_SECRET
> 
> @osala-eng I just remembered about the other repo with the manifest file which answer my original question sufficiently.
> 
> New related question about the env var names. You went with the SDK built-in names rather than our usual pattern of prefixing with "DOCQ_". Was that intentional for reasons like it's the only way to use the SDK? I wanted to check before refactoring to save myself some pain :)

Yes, you can customize the env var names, then pass them explicitly when instanciating the `SlackOauthFlow` class. By default, slack_sdk looks for the names provided in their documentation.

2024-04-06 19:37 UTC, janaka approved these changes

2024-04-06 19:40 UTC, janaka commented on source/docq/integrations/slack/slack_application.py
> +USER_SCOPES = ["admin"]
I've removed the user_scopes `admin` for now. As I understood from the docs user scopes allow the bot to do things on behalf of a user / as a user with those perms. maybe I've misunderstood. Will revisit.

2024-04-06 19:47 UTC, merged