Bug/fix sources
docqai/docq pull request #66
Opened 2023-07-18 12:12 UTC by osala-eng

## Description

Please include a summary of the change, e.g. what the new feature # is and/or what bug # it fixes. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes/Implements #(issue/feature)
- Made links to sources space aware

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [ ] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] The commit message follows the convention of this project

2023-07-18 13:42 UTC, cwang commented on tests/docq/manage_documents_test.py
> +#     assert format_document_sources(source_nodes, space) == expected
Are these lines no longer needed? Or they should be put back?

2023-07-18 13:53 UTC, cwang commented on source/docq/data_source/support/data_source_handler.py
> +class Source:
Frankly I don't see the point of having such a big ceremony of so many lines of code with perhaps only 3-4 lines of useful code. This could be solved by having a single function if I read it correctly.

2023-07-18 13:55 UTC, cwang commented on source/docq/data_source/support/data_source_handler.py
> +class DataSourceType(Enum):
Isn't it a duplicate of what's already been defined?

2023-07-18 13:59 UTC, cwang commented on source/docq/manage_documents.py
> +                    source_types = source.group_source_uri(s_type, file_name, source_types)
One function to spit out a tuple of these 3 variables would be sufficient unless I missed anything.

2023-07-18 16:47 UTC, osala-eng commented on source/docq/data_source/support/data_source_handler.py
> +class DataSourceType(Enum):
I have not seen this defined anywhere.

2023-07-18 16:54 UTC, osala-eng commented on source/docq/data_source/support/data_source_handler.py
> +class Source:
Are we sure all the data sources will have the same parameters, currently this only implements handling `Manual Uploads` fully I'm still adding code to handle the other data sources `Azure Blob`, `AWS S3`, and the `Web Scrapers`

2023-07-18 17:00 UTC, osala-eng commented on source/docq/manage_documents.py
> +                    source_types = source.group_source_uri(s_type, file_name, source_types)
Okay, let me re-do this

2023-07-18 17:01 UTC, osala-eng commented on tests/docq/manage_documents_test.py
> +#     assert format_document_sources(source_nodes, space) == expected
Adding the test for this after handling all the data sources.

2023-07-19 11:23 UTC, cwang commented
Is this ready for another look? Could you post some screenshots for the fixed source links? When I ran it locally it doesn't seem to give me any source links.

2023-07-19 12:43 UTC, osala-eng commented
> Is this ready for another look? Could you post some screenshots for the fixed source links? When I ran it locally it doesn't seem to give me any source links.

Yes, this is ready for a look, here are some sample screenshots.


#### Shared Space
![shared-space](https://github.com/docqai/docq/assets/64925863/82c934c1-7177-4e9b-ad7e-e8b1c29ff266)

#### Personal space
![personal-docs](https://github.com/docqai/docq/assets/64925863/ca5df64a-77de-4918-af4d-17203705848f)

2023-07-19 12:52 UTC, cwang commented
Nice, can see it now when running locally. Does it work with web and kb scrapers based spaces?

2023-07-20 09:03 UTC, osala-eng commented
@janaka The datasouces `AWS S3`, `Azure Blob` and `Web Scraper` do not provide any metadata info in the response object. Could you take a look at this pls.

2023-07-20 11:38 UTC, janaka commented
> @janaka The datasouces `AWS S3`, `Azure Blob` and `Web Scraper` do not provide any metadata info in the response object. Could you take a look at this pls.

Here you can see what's in metadata for the web scraper ( or others inheriting from that `SpaceDataSourceWebBased`). 
Manual upload will also have these. At the moment Azure blob (and AWS S3 though no implementation yet) doesn't have data source type. This is because we are using a community loader that doesn't have a first-class way to add metadata
![image](https://github.com/docqai/docq/assets/51779/f6df1dfe-3269-4a3d-8e21-8f494afb46a9).

I've also just spotted that the names of those fields are wrong, showing the display name. `DocumentMetadata` enum is where the names are defined. You can base this fix on this for now while I push a fix for the names. I'll see if meta data can be improved to help.

2023-07-20 13:36 UTC, osala-eng commented
> > @janaka The datasouces `AWS S3`, `Azure Blob` and `Web Scraper` do not provide any metadata info in the response object. Could you take a look at this pls.
> 
> Here you can see what's in metadata for the web scraper ( or others inheriting from that `SpaceDataSourceWebBased`). Manual upload will also have these. At the moment Azure blob (and AWS S3 though no implementation yet) doesn't have data source type. This is because we are using a community loader that doesn't have a first-class way to add metadata.
> 
> ![image](https://user-images.githubusercontent.com/51779/254868179-f6df1dfe-3269-4a3d-8e21-8f494afb46a9.png)
> 
> I've also just spotted that the names of those fields are wrong, showing the display name. `DocumentMetadata` enum is where the names are defined. You can base this fix on this for now while I push a fix for the names. I'll see if meta data can be improved to help.

I've based the fix on this for the web scrapper data source for now.


#### Sample `Web Scraper` Space
![web_scrapper](https://github.com/docqai/docq/assets/64925863/e6ec844e-5651-468b-9bc5-abeab1c6d199)

2023-07-20 14:27 UTC, janaka commented
@osala-eng try you fix in this branch and see if it works. Will cut a PR after that.

I had a look at a way to get the file names but I can't find a way as is. This data source is going to be refactored to use our own loader rather than the community one, better control over metadata is one of the key reasons.

2023-07-20 14:36 UTC, cwang commented
Yes let's get this PR merged first and fix Azure data source later

2023-07-20 15:30 UTC, osala-eng commented
Okay

2023-07-21 12:47 UTC, janaka commented
> #### Grouped pages under site:
> <img alt="format-pages" width="601" src="https://user-images.githubusercontent.com/64925863/254961857-083d48f9-7df7-4508-b119-ba5eee171fd3.png">

yeah that works. 

What's the X next to each source

![image](https://github.com/docqai/docq/assets/51779/15b31924-4a4c-4703-9853-59306acb6c22)


Couple more things:
- zero sources case - Right now it renders "Source(s):" I think the best experience for now is to not show anything.
- one source vs multiple - for once "Source:" for multiple "Sources:"

2023-07-22 11:47 UTC, cwang commented
Sorry pls rebase as the other PR went in first

2023-07-25 07:19 UTC, osala-eng commented
##### Updated the source lists to use updates from #74 
![ask_shared_space](https://github.com/docqai/docq/assets/64925863/0ef9fd1d-96e8-413e-ab7c-08ea8b4e6c47)

2023-07-25 08:41 UTC, cwang commented on source/docq/manage_documents.py
> +    if s_name == SpaceDataSources.WEB_SCRAPER.value.get_name() or s_name ==  SpaceDataSources.KNOWLEDGE_BASE_SCRAPER.value.get_name():
Recalling what's in #74 let's lose `lower()` all over the place.
Also I don't see `DATA_SOURCE_TYPE` being used anywhere?

2023-07-25 13:14 UTC, osala-eng commented on source/docq/manage_documents.py
> +    if s_name == SpaceDataSources.WEB_SCRAPER.value.get_name() or s_name ==  SpaceDataSources.KNOWLEDGE_BASE_SCRAPER.value.get_name():
Okay

2023-07-31 04:28 UTC, osala-eng commented
I'm currently working on Azure blob and S3 loaders, to configure metadata properly

2023-07-31 07:22 UTC, cwang commented
No need to implement S3 scraper unless it was agreed upon beforehand?

2023-07-31 07:32 UTC, osala-eng commented
> No need to implement S3 scraper unless it was agreed upon beforehand?

Okay

2023-07-31 10:01 UTC, janaka commented
> I'm currently working on Azure blob and S3 loaders, to configure metadata properly
>> No need to implement S3 scraper unless it was agreed upon beforehand?
+1 don't worry about the S3 scrapper. That's only a stubb at the moment.

2023-07-31 10:12 UTC, janaka commented
>I'm currently working on Azure blob and S3 loaders, to configure metadata properly

Also re-writing the Azure Blob loader isn't supposed to be part of this scope. Want to try and do this using OpenDAL (I started on #61 last week).

I thought I had mentioned this intention. Sorry if this wasn't clear.

2023-07-31 11:57 UTC, osala-eng commented
> > I'm currently working on Azure blob and S3 loaders, to configure metadata properly
> 
> Also re-writing the Azure Blob loader isn't supposed to be part of this scope. Want to try and do this using OpenDAL (I started on #61 last week).
> 
> I thought I had mentioned this intention. Sorry if this wasn't clear.

Alright, let me undo the changes.

2023-08-01 10:16 UTC, osala-eng commented on source/docq/manage_documents.py
> +    s_name = metadata.get(str(DocumentMetadata.DATA_SOURCE_NAME.name).lower())
Done, I've used `DATA_SOURCE_TYPE` to distinguish between file and web based sources

2023-08-01 10:24 UTC, osala-eng commented on source/docq/data_source/azure_blob.py
> +                    DocumentMetadata.SPACE_TYPE.name: space.type_.name,
I've reverted this back to match whats on main as we discussed yersterday.

2023-08-01 10:28 UTC, osala-eng commented on source/docq/manage_documents.py
> +    if s_name == SpaceDataSources.WEB_SCRAPER.value.get_name() or s_name ==  SpaceDataSources.KNOWLEDGE_BASE_SCRAPER.value.get_name():
Okay, this is all sorted now.

2023-08-01 10:40 UTC, osala-eng commented
This is ready for review.

2023-08-01 11:08 UTC, janaka requested changes
Great, this is a smaller change now. I left a few comments about looking at making the code simpler.

2023-08-01 11:08 UTC, janaka commented on source/docq/manage_documents.py
> +                _sources.append(f"> *File:* [{name}]({download_url})<br> *Pages:* {', '.join(page_labels)}")
Can you look at refactoring to make the logic easier to follow and easier to extend when we add more types of sources like a CRM. This feels more complicated to follow the logic than it should be. Ideally, there are cases for any specifics for types and common fields handled as the default.

2023-08-01 11:31 UTC, osala-eng commented on source/docq/manage_documents.py
> +    if s_type == 'SpaceDataSourceWebBased':
Okay

2023-08-01 11:36 UTC, osala-eng commented on source/docq/manage_documents.py
> +        page_title = _remove_ascii_control_characters(metadata.get("page_title"))
Some sites like https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html#installation-and-setup, has a permalink to the `title` which renders as a `x` which you previously asked about and sometimes the webscrapper captures the site title with a number of carriage returns which breaks the UI when rendered directly using markdown.

2023-08-01 11:39 UTC, janaka commented on source/docq/manage_documents.py
> +        page_title = _remove_ascii_control_characters(metadata.get("page_title"))
yes, I remember. OK leave it like this for now. I've move it to the data source when I'm in it.

2023-08-01 11:44 UTC, osala-eng commented on source/docq/manage_documents.py
> +                _sources.append(f"> *File:* [{name}]({download_url})<br> *Pages:* {', '.join(page_labels)}")
Okay

2023-08-02 08:26 UTC, osala-eng commented
I've refactored source_formatter to allow easy extension

2023-08-03 09:19 UTC, janaka commented
@osala-eng introducing a whole load of class abstraction is over the top here. There's not enough domain or logic complexity, or repetition IMO to justify.

`if` statements on source type structured in clear blocks should achieve thr requirement I mentioned previously.

2023-08-08 09:17 UTC, janaka commented
@osala-eng are you close on this?

2023-08-08 09:51 UTC, osala-eng commented
> @osala-eng are you close on this?

Yes, I'm updating this now.

2023-08-09 06:18 UTC, osala-eng commented
@janaka This is ready for another look.
![image](https://github.com/docqai/docq/assets/64925863/12fcf1f3-590e-4115-999d-b998a9b82d5c)

2023-08-09 11:36 UTC, cwang reviewed
As long as it works :)

2023-08-09 11:36 UTC, cwang commented on web/utils/layout.py
> +        chat_ui(*args, **kwargs)
Why cannot this piece of `st.write` code be directly embedded into `chat_ui` function?

2023-08-09 11:45 UTC, osala-eng commented on web/utils/layout.py
> +        chat_ui(*args, **kwargs)
Okay, I can do embed it directly. Just thought it would make the function too long if more custom `css` is needed in future.

2023-08-09 13:13 UTC, janaka approved these changes
Nice, looks good! easy to understand and should be pretty easy to further refactor in the future if we need to.

2023-08-09 13:21 UTC, merged