Bug/ux reloading pages
docqai/docq pull request #77
Opened 2023-08-03 10:09 UTC by osala-eng

## Description

Please include a summary of the change, e.g. what the new feature # is and/or what bug # it fixes. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes/Implements #(issue/feature)
Fixes page goes to login page on page reload even if you have already logged in.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [X] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] The commit message follows the convention of this project

2023-08-03 18:15 UTC, janaka requested changes
Nice I think this is looking pretty good for our needs now. I left a few comments.

@cwang this one can do with another pair of eyes. Replay attacks are the main exposure I was worried about leaving open but encrypting the hash mitigates that fine.

2023-08-03 18:15 UTC, janaka commented on source/docq/support/auth_utils.py
> +            document.cookie = "{COOKIE_NAME}={cookie}; expires={expiry.strftime('%a, %d %b %Y %H:%M:%S GMT')}; path=/;";
Have you checked what `Domain` is set to? I think when not set explicitly the default behaviour is secure i.e. it should be auto-set to what ever domain the request came on. This makes sure an app on another domain cannot read these secret cookies.

2023-08-04 06:15 UTC, osala-eng commented on source/docq/manage_settings.py
> +def _get_settings(user_id: int | None = None) -> dict:
Yes, this gets called when calling `_get_sqlite_file()`

2023-08-04 06:18 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +COOKIE_SECRET = "secret_key"
Okay, I'm renaming the secret key and adding a validation for the number of bits.

2023-08-04 06:20 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +session_data:TTLCache[str, str]= TTLCache(*CACHE_CONFIG)
I'm adding a variable at the top to control both the local cache duration and the client side cookie expiry.

2023-08-04 07:02 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +            return cookie
Yes, if a cookie is invalid a login screen is presented.

2023-08-04 07:09 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +    hmac_ = _create_hmac(id_)
Apart from the `key` and `salt` the rest basically depends on our needs. i.e We could lock the sessions to a specific `IP address`, e.t.c

2023-08-04 07:10 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +            document.cookie = "{COOKIE_NAME}={cookie}; expires={expiry.strftime('%a, %d %b %Y %H:%M:%S GMT')}; path=/;";
Yes, this is locked to the domain that the request came from.

2023-08-04 07:11 UTC, osala-eng commented on source/docq/support/auth_utils.py
> +        expiry = datetime.now() + timedelta(hours=4)
Not yet a sliding window, let me add that.

2023-09-06 14:32 UTC, cwang reviewed
Left a few comments. More significantly, when running this branch, I'm getting

![Screenshot 2023-09-06 at 15 31 42](https://github.com/docqai/docq/assets/166679/c5ae227a-952f-4392-b0e8-ef2101ed6df9)

(having done `poe install`)

2023-09-06 14:32 UTC, cwang commented on web/utils/handlers.py
> +            )
Some bad indentations between L48 and L60?

2023-09-06 14:32 UTC, cwang commented on source/docq/support/utils.py
> +"""Cache user sessions."""
Why cannot this be put in the `sessions.py` file in the same directory, given the same purpose?

2023-09-06 14:32 UTC, cwang commented on source/docq/support/auth_utils.py
> +"""Cache user sessions."""
I'm surprised that you had to do it by using crypto apis directly - presumably none of the encrypted cookie plugins would do the job?

2023-09-06 14:32 UTC, cwang commented on source/docq/manage_users.py
> +from .support.utils import cache_auth
Which one is actually used, between L16 and L18?

2023-09-06 14:40 UTC, janaka commented on source/docq/support/auth_utils.py
> +"""Cache user sessions."""
which plugins were you thinking specifically?

2023-09-06 14:42 UTC, cwang commented on source/docq/support/auth_utils.py
> +"""Cache user sessions."""
Something like https://pypi.org/project/streamlit-cookies-manager/ but there're more

2023-09-10 17:06 UTC, janaka commented on source/docq/support/auth_utils.py
> +"""Cache user sessions."""
Note: added some info here https://github.com/docqai/docq/issues/37#issuecomment-1712877001

2023-09-11 11:10 UTC, osala-eng commented
Moving this to #97

2023-09-11 11:10 UTC, closed without merging