Bug/ux reloading pages new
docqai/docq pull request #97
Opened 2023-09-11 11:09 UTC by osala-eng

## Description

Please include a summary of the change, e.g. what the new feature # is and/or what bug # it fixes. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes/Implements #(issue/feature)
Fixes page goes to login page on page reload even if you have already logged in.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor and code improvement (non-breaking change which improves code quality and/or performance)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation
- [X] Tests
- [ ] Other chores such as maintenance

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration by modifying the list below.

- [ ] Test A
- [ ] Test B
- [ ] Test C

**Test Configuration**:

Please describe the test setup. List them below as bullet points.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] The commit message follows the convention of this project

2023-09-11 15:46 UTC, osala-eng commented
> @osala-eng feature toggle change you mentioned on email is yet to be pushed right?

Yes

2023-09-11 20:10 UTC, janaka commented
@cwang do you also want to review the feature toggle change? I've had a look and lgtm

2023-09-12 13:51 UTC, janaka commented
@osala-eng is this rebased on latest main?

2023-09-12 14:00 UTC, cwang commented on web/utils/handlers.py
> +            [domain.SpaceKey(config.SpaceType.SHARED, s_[0]) for s_ in list_public_space_group_members()],
Again wanted to double check if this is correct (from `PUBLIC` to `SHARED`)?

2023-09-12 14:00 UTC, janaka commented
@osala-eng 
When I login and hit refresh I get logged out and I get the following error in the console. I delete `.persisted` then stop started the app.
>2023-09-12 14:59:22,782 ERROR Failed to check if auto login is enabled: argument of type 'NoneType' is not iterable

2023-09-12 14:03 UTC, osala-eng commented
> @osala-eng When I login and hit refresh I get logged out and I get the following error in the console. I delete `.persisted` then stop started the app.
> 
> > 2023-09-12 14:59:22,782 ERROR Failed to check if auto login is enabled: argument of type 'NoneType' is not iterable

Let me take a look.

2023-09-12 14:04 UTC, cwang commented on web/utils/sessions.py
> +    return _get_session_value(SessionKeySubName.PUBLIC, SessionKeyNameForPublic.SESSION.name)
Is the enum `SessionKeyNameForPublic` already in main?

2023-09-12 14:10 UTC, osala-eng commented on web/utils/handlers.py
> +            [domain.SpaceKey(config.SpaceType.SHARED, s_[0]) for s_ in list_public_space_group_members()],
Yes, this points to the `Indexes` for public spaces which are stored under `SHARED`.

2023-09-12 14:10 UTC, osala-eng commented on web/utils/sessions.py
> +    return _get_session_value(SessionKeySubName.PUBLIC, SessionKeyNameForPublic.SESSION.name)
Yes

2023-09-12 14:17 UTC, janaka commented on source/docq/manage_settings.py
> +        sqlite3.connect(_get_sqlite_file(), detect_types=sqlite3.PARSE_DECLTYPES) # FIXME: fix sqlite3.OperationalError: no such table: settings if user_id is not None
I gues this is a work around given the FIXME comment? but this change will break a bunch of stuff surely

2023-09-12 14:23 UTC, osala-eng commented on source/docq/config.py
> +    AUTO_LOGIN = "Auto Login"
I added this as a `feature` to enable or disable re-authenticating on page reload. Not for the public sessions.

2023-09-12 14:28 UTC, janaka commented on source/docq/manage_settings.py
> +        sqlite3.connect(_get_sqlite_file(), detect_types=sqlite3.PARSE_DECLTYPES) # FIXME: fix sqlite3.OperationalError: no such table: settings if user_id is not None
Looking at this closer, it seems like even the original logic will fail for system settings. When you login as a different user. Maybe best to fix that up on my branch given it's dealing with org scope settings.

2023-09-12 14:31 UTC, osala-eng commented on source/docq/manage_settings.py
> +        sqlite3.connect(_get_sqlite_file(), detect_types=sqlite3.PARSE_DECLTYPES) # FIXME: fix sqlite3.OperationalError: no such table: settings if user_id is not None
Sorry, I missed this when rebasing the fix was applied by #80

2023-09-12 14:38 UTC, janaka commented
@osala-eng I presume these are all changes fixes you are slipping into this PR rather than being strictly related to the Auth feature?

2023-09-12 14:44 UTC, osala-eng commented
> @osala-eng I presume these are all changes fixes you are slipping into this PR rather than being strictly related to the Auth feature?

I've refactored some code after merging #95  to avoid having duplicates

2023-09-12 15:42 UTC, osala-eng commented
> The error has gone now. I still get logged out when I refresh.

This is disabled by default, You have to enable `Auto Login` in `Admin Settings`

2023-09-12 15:52 UTC, janaka commented
> > The error has gone now. I still get logged out when I refresh.
> 
> This is disabled by default, You have to enable `Auto Login` in `Admin Settings`

seems to be enabled by default for me.

2023-09-12 16:11 UTC, osala-eng commented
> > > The error has gone now. I still get logged out when I refresh.
> > 
> > 
> > This is disabled by default, You have to enable `Auto Login` in `Admin Settings`
> 
> seems to be enabled by default for me.

You have to click the save button on the `Admin Settings` page to make the `system settings` defined on a new instance of docq.

2023-09-12 16:15 UTC, osala-eng commented
@janaka Should I make this enabled by default if system settings are not defined?

2023-09-12 16:31 UTC, janaka commented
There's something weird doing on when booting up a new instance on the app. 

- setting page show Auto Login in the list, which I take as enabled. If it's disabled by default why is it appearing here? 

- Hitting save on the settings page is throwing an error in the console. I've tried removing Auto Login and re-adding. Still get the error.

If you are free let's jump on a call an hash out.

2023-09-12 17:11 UTC, janaka commented
I created #99 to handle default setting issue. 

Note: once auto login has been enabled and settings saved, the user needs to logout and login for this particular feature to take effect. When it has, hitting refresh will not log the user out.

2023-09-12 17:16 UTC, janaka commented
@osala-eng Sound like should be SameSite=strict. I don't think a auth token cookie should be sharable in the way lax does it I've understood it correctly.

2023-09-13 13:07 UTC, janaka approved these changes

2023-09-13 13:53 UTC, cwang requested changes
Blocking temporarily so it's not merged for now before I have another look.

2023-09-13 13:53 UTC, cwang commented on web/utils/handlers.py
> +            [domain.SpaceKey(config.SpaceType.SHARED, s_[0]) for s_ in list_public_space_group_members()],
I don't understand this, why did it become incorrect after this change?

2023-09-13 13:53 UTC, cwang commented on web/utils/sessions.py
> +    return _get_session_value(SessionKeySubName.PUBLIC, SessionKeyNameForPublic.SESSION.name)
I have some opinions about these names in general but it's okay for now.
Also I think this change should've belonged to another PR?

2023-09-13 13:53 UTC, cwang commented on source/docq/config.py
> +    AUTO_LOGIN = "Auto Login"
This is really not ideal because it abuses the actual meaning of the definition here.

2023-09-13 14:05 UTC, cwang commented
Is 32 really necessary, or just easy for us to make it so to satisfy the underlying crypto lib? 
<img width="507" alt="Screenshot 2023-09-13 at 15 03 57" src="https://github.com/docqai/docq/assets/166679/c7758e99-92fe-4045-af8e-75d5249e62b6">

2023-09-18 09:21 UTC, janaka commented
> Chat (api calls to openai) seems to be broken, probably not because of this PR.

note to help keep track: as suspected this was caused by a missing LlamaIndex dependency (NLTK). It's unclear how this got out of sync. Was fixed by bumping LlamaIndex to the latest stable version, removing the LlamaIndex, then adding again.

2023-09-27 10:40 UTC, osala-eng commented
Reapplied this in #111

2023-09-27 10:40 UTC, closed without merging